server:
    port: 8092
    contextPath: /dartxrating

spring:
    application:
        name: dart-x-rating-api
    data:
      mongodb:
        uri: mongodb://localhost/dartxrating

management:
    contextPath: /manage
